name: Cloudflare Workers
on:
  push:
  workflow_dispatch:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
    - name: Build
      run: deno run -A scripts/build_cloudflare_workers.ts
    - uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
