name: Fermyon Cloud
on:
  push:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
    - name: Install Spin
      uses: fermyon/actions/spin/setup@v1
      with:
        plugins: js2wasm
    - name: Install dependencies
      run: npm install @fermyon/spin-sdk
    - name: Build & Deploy
      uses: fermyon/actions/spin/deploy@v1
      with:
        fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}
